# 应用配置
app:
  env: "dev"  # 环境: dev, prod, test
  port: 8080
  session_secret: "your-session-secret-key-change-in-production"

# 数据库配置
database:
  host: "localhost"
  port: 15432
  user: "postgres"
  password: "admin"
  name: "acme"

# 日志配置
log:
  level: "info"  # debug, info, warn, error
  file: "logs/app.log" 